### ISSUE TITLE
Publish dashboard

### ISSUE THREAD

**Issue by rngadam** [coderbunker/timesheet-dashboard#2]
* create a Github project page for the dashboard: 
  * https://pages.github.com/
* setup dashboard.coderbunker.com
  * https://help.github.com/articles/setting-up-a-custom-subdomain/

**Comment by sam123evers** [comment]
Seems like I need some log in information to access google DNS services

**Comment by sam123evers** [comment]
I feel like I am not doing this correctly:
Do I need an A name record to point to the github pages I.P. address also?

![screen shot 2018-04-27 at 4 07 38 pm](https://user-images.githubusercontent.com/25334488/39351867-7747a6ae-4a35-11e8-9ff0-c2615b0632ae.png)

![screen shot 2018-04-27 at 4 07 58 pm](https://user-images.githubusercontent.com/25334488/39351869-79b63086-4a35-11e8-9a42-fa4fc1f2289a.png)

![screen shot 2018-04-27 at 4 08 08 pm](https://user-images.githubusercontent.com/25334488/39351871-7c2fd45c-4a35-11e8-9c29-53325dd44357.png)

![screen shot 2018-04-27 at 4 08 28 pm](https://user-images.githubusercontent.com/25334488/39351874-7f54cd36-4a35-11e8-8a83-e0e61b304e5b.png)

**Comment by sam123evers** [comment]
dashboard.coderbunker.com redirects to the gh-pages site, but displays the gh-pages url upon doing so.

**Comment by rngadam** [comment]
Yup, completely wrong. It's not a redirection we want, we want an alias record.

* CNAME should contain dashboard.coderbunker.com
* CNAME record in the DNS should point to  coderbunker.github.io

**Comment by rngadam** [comment]
Deleted this:

<img width="822" alt="screen shot 2018-04-28 at 8 19 59 am" src="https://user-images.githubusercontent.com/538542/39389641-ff98c952-4abc-11e8-82ff-7f475e4d97b4.png">

Edited this:

<img width="882" alt="screen shot 2018-04-28 at 8 20 24 am" src="https://user-images.githubusercontent.com/538542/39389640-ff6a8ff6-4abc-11e8-9a3d-bebaa2d012e1.png">

Updated this:

<img width="996" alt="screen shot 2018-04-28 at 8 21 00 am" src="https://user-images.githubusercontent.com/538542/39389639-ff3b579a-4abc-11e8-8cb9-11b52ae3414f.png">

Tested by looking up on the Google DNS:

<img width="641" alt="screen shot 2018-04-28 at 8 21 26 am" src="https://user-images.githubusercontent.com/538542/39389638-ff06be5e-4abc-11e8-8e34-d0e1274c5e19.png">

**Comment by rngadam** [comment]
Check propagation:

<img width="1010" alt="screen shot 2018-04-28 at 8 26 40 am" src="https://user-images.githubusercontent.com/538542/39389714-bb8534fc-4abd-11e8-8e70-c5867d21067c.png">

Changed DNS temporarily to Google DNS (my ISP had not the changes yet):

<img width="577" alt="screen shot 2018-04-28 at 8 26 28 am" src="https://user-images.githubusercontent.com/538542/39389715-bbb952be-4abd-11e8-8bd4-a3709770ea42.png">

Test:

<img width="543" alt="screen shot 2018-04-28 at 8 27 40 am" src="https://user-images.githubusercontent.com/538542/39389725-dc0252e6-4abd-11e8-89e4-f830faa607ac.png">

**Comment by rngadam** [comment]
Done.
